services:
  - type: web
    name: ifpe-inteligente
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt


    startCommand: gunicorn app:app --workers 1 --threads 1 --timeout 120
